name: qualitydoc-node

services:

  db-mongodb:
    image: mongo:6.0.16
    container_name: db-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ../db/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - qualitydoc-net
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  search-service:
    build:
      context: ../src/node-service
      dockerfile: ../../docker/node.Dockerfile
    container_name: search-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://db-mongodb:27017/qualitydoc
      - NODE_ENV=production
      - AUTH_API_URL=http://admin-dotnet:8080/api/login
    depends_on:
      db-mongodb:
        condition: service_healthy
    networks:
      - qualitydoc-net

networks:
  qualitydoc-net:
    name: qualitydoc-net
    external: true

volumes:
  mongo_data:
