name: qualitydoc-php

services:

  db-postgres:
    image: postgres:16.3-alpine3.20
    container_name: db-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sgd_user
      POSTGRES_PASSWORD: sgd_password
      POSTGRES_DB: sgd_db
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - qualitydoc-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sgd_user -d sgd_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  web-php:
    build:
      context: ../src/php-app
      dockerfile: ../../docker/php.Dockerfile
    container_name: web-php
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db-postgres
      - DB_PORT=5432
      - DB_NAME=sgd_db
      - DB_USER=sgd_user
      - DB_PASSWORD=sgd_password
      - AUTH_API_URL=http://admin-dotnet:8080/api/login
    volumes:
      - ../src/php-app:/var/www/html
      - uploads_shared:/var/www/html/uploads
    depends_on:
      db-postgres:
        condition: service_healthy
    networks:
      - qualitydoc-net

networks:
  qualitydoc-net:
    name: qualitydoc-net
    external: true

volumes:
  pg_data:
  uploads_shared:
