events {
    worker_connections 1024;
}

http {
    # Incluimos los tipos mime estándar que ya vienen en el contenedor nginx
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # ¡ESTO ES CLAVE! Permite subir archivos de hasta 30MB (o lo que necesites)
    client_max_body_size 30M;

    server {
        listen 80;

        # 1. Servir documentos (Static Files)
        location /uploads/ {
            alias /usr/share/nginx/html/uploads/;
            # Opcional: añade esto para seguridad
            autoindex off;
        }

        # 2. Enviar todo lo demás a tu App .NET
        location / {
    # Cambia el 80 por 8080
        proxy_pass http://admin-net:8080; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
    }
}